### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by djtm** [Arubacloud/vagrant-arubacloud#2]
I get this error after vagrant up.

vagrant version
Installed Version: 1.8.6
Latest Version: 1.9.2

Ubuntu 16.04

`/.vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/action/create_server.rb:74:in `rescue in call': undefined method `[]' for nil:NilClass (NoMethodError)
        from .vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/action/create_server.rb:68:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
        from .vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/action/connect_arubacloud.rb:33:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:225:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:200:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:567:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:186:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:186:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'`

`
#vagrant arubacloud servers
==> centos: Server Name          State                IPv4 address
.vagrant.d/gems/gems/fog-arubacloud-0.0.3/lib/fog/arubacloud/requests/compute/get_servers.rb:32:in `get_servers': {"ExceptionInfo"=>nil, "ResultCode"=>2, "ResultMessage"=>"Authentication failed, invalid username.\r\nExceptionCode=2\r\n", "Success"=>false} (Fog::ArubaCloud::Errors::RequestError)
        from .vagrant.d/gems/gems/fog-arubacloud-0.0.3/lib/fog/arubacloud/models/compute/servers.rb:24:in `all'
        from .vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/collection.rb:113:in `lazy_load'
        from .vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/collection.rb:17:in `each'
        from .vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/action/list_servers.rb:12:in `sort_by'
        from .vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/action/list_servers.rb:12:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
        from .vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/action/connect_arubacloud.rb:33:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:225:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:200:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:567:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:186:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:186:in `action'
        from .vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/command/servers.rb:15:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/plugin/v2/command.rb:229:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
        from .vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/command/servers.rb:14:in `execute'
        from .vagrant.d/gems/gems/vagrant-arubacloud-0.0.3/lib/vagrant-arubacloud/command/root.rb:40:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:308:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:174:in `<main>'
`

Apparently the **AWI username** is necessary. Then I get:
`.vagrant.d/gems/gems/fog-arubacloud-0.0.3/lib/fog/arubacloud/requests/compute/get_servers.rb:32:in `get_servers': {"ExceptionInfo"=>nil, "ResultCode"=>2, "ResultMessage"=>"Authentication failed, token not found.\r\nExceptionCode=2\r\n", "Success"=>false} (Fog::ArubaCloud::Errors::RequestError)`

**Comment by arubalucalasagni** [comment]
For now, you have to specify your username and password as environment variables:
export AC_USERNAME="your-username"
export AC_PASSWORD="your-pwd"

**Comment by djtm** [comment]
I did. Please see at the end of my post.

**Comment by arubalucalasagni** [comment]
we did a check up of the plugin and we fixed some bugs. Now the vagrant up problems are vanished. Follow up the README.md file to find out any response.

**Comment by djtm** [comment]
thank you, it does seem to work now.
