### ISSUE TITLE
vagrant plugin install vagrant-arubacloud fails

### ISSUE THREAD

**Issue by unigia** [Arubacloud/vagrant-arubacloud#3]
When I install the plugin on Ubuntu Desktop 7.10, I get the following error:

Installing the 'vagrant-arubacloud' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:2289:in `raise_if_conflicts': Unable to activate fog-1.42.0, because json-1.8.3 conflicts with json (~> 2.0) (Gem::ConflictError)
        from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:323:in `block in activate_solution'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `each'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `activate_solution'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:248:in `internal_install'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:98:in `install'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `install_plugin'        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/commands/plugin/action/install_gem.rb:37:in `call'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/commands/plugin/command/base.rb:14:in `action'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `each'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `execute'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:274:in `cli'
        from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/bin/vagrant:122:in `<top (required)>'
        from /usr/bin/vagrant:22:in `load'
        from /usr/bin/vagrant:22:in `<main>'

**Comment by arubalucalasagni** [comment]
It seems you have the version 1.8.3 of the gem **json** instead of a varsion greater then 2.0.
You should make an update of the gem **json** to the last version. 
You can execute the following command: 
```
sudo gem update json
```
but you should got this error:
```
Updating json
Fetching: json-2.1.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/json-2.1.0/ext/json/ext/generator
/usr/bin/ruby2.3 -r ./siteconf20180313-56238-ugifb.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/json-2.1.0 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/json-2.1.0/gem_make.out
```

To resolve it you need to install the **ruby-dev** package to compile the gem:
```
apt-get sudo install ruby-dev
```
and after when you have updated the json gem you can run:
```
vagrant plugin install vagrant-arubacloud
```

**Comment by unigia** [comment]
Thank you very much, now it works!
