### ISSUE TITLE
problem with install plugin on windows 7

### ISSUE THREAD

**Issue by jabocrack1** [Arubacloud/vagrant-arubacloud#4]
D:\webroot>vagrant plugin install vagrant-arubacloud
Installing the 'vagrant-arubacloud' plugin. This can take a few minutes...
Fetching: excon-0.62.0.gem (100%)
Fetching: formatador-0.2.5.gem (100%)
Fetching: fog-core-1.45.0.gem (100%)
Fetching: fog-json-1.0.2.gem (100%)
Fetching: mini_portile2-2.3.0.gem (100%)
Fetching: nokogiri-1.8.2-x86-mingw32.gem (100%)
Nokogiri is built with the packaged libraries: libxml2-2.9.7, libxslt-1.1.32, zlib-1.2.11, libiconv-1.15.
Fetching: fog-xml-0.1.3.gem (100%)
Fetching: ipaddress-0.8.3.gem (100%)
Fetching: xml-simple-1.1.5.gem (100%)
Fetching: fog-aliyun-0.2.1.gem (100%)
Fetching: fog-atmos-0.1.0.gem (100%)
Fetching: fog-aws-2.0.1.gem (100%)
Fetching: inflecto-0.0.2.gem (100%)
Fetching: fog-brightbox-0.14.0.gem (100%)
Fetching: fog-cloudatcost-0.1.2.gem (100%)
Fetching: fog-digitalocean-0.3.0.gem (100%)
Fetching: fog-dnsimple-1.0.0.gem (100%)
Fetching: fog-dynect-0.0.3.gem (100%)
Fetching: fog-ecloud-0.3.0.gem (100%)
Fetching: fog-google-0.1.0.gem (100%)
Fetching: fog-internet-archive-0.0.1.gem (100%)
Fetching: fog-joyent-0.0.1.gem (100%)
Fetching: fog-local-0.5.0.gem (100%)
Fetching: fog-openstack-0.1.25.gem (100%)
Fetching: ovirt-engine-sdk-4.2.4.gem (100%)
Building native extensions.  This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: C:/Users/jabocrack/.vagrant.d/gems/2.4.4/gems/ovirt-engin
e-sdk-4.2.4/ext/ovirtsdk4c
D:/HashiCorp/Vagrant/embedded/mingw32/bin/ruby.exe -r ./siteconf20180421-12688-x
150pa.rb extconf.rb
checking for xml2-config... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/HashiCorp/Vagrant/embedded/mingw32/bin/$(RUBY_BASE_NAME)
        --with-libxml2-config
        --without-libxml2-config
        --with-pkg-config
        --without-pkg-config
extconf.rb:29:in `<main>': The "libxml2" package isn't available. (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can
 be found here:

  C:/Users/jabocrack/.vagrant.d/gems/2.4.4/extensions/x86-mingw32/2.4.0/ovirt-en
gine-sdk-4.2.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Users/jabocrack/.vagrant.d/gems/2.4.4/gems
/ovirt-engine-sdk-4.2.4 for inspection.
Results logged to C:/Users/jabocrack/.vagrant.d/gems/2.4.4/extensions/x86-mingw3
2/2.4.0/ovirt-engine-sdk-4.2.4/gem_make.out

---

vagrant 2.0.4 x32, windows 7 x64

**Comment by arubalucalasagni** [comment]
We have removed unuseful dependencies, now the problem is resolved you can reinstall the vagrant-arubacloud plugin. There is a new version in rubygems repo.
It's enough for you reinstall the plugin using vagrant plugin commands.
